"""FreeCAD script generator — turn TubeSpecs into a standalone macro."""

from .geometry import TubeSpec, ParameterizedSocket


class FreeCADScriptGenerator:
    """Generate a standalone FreeCAD Python macro from tubes and dropouts."""

    def __init__(self, tubes: list[TubeSpec], hollow: bool = False,
                 dropouts: list[ParameterizedSocket] | None = None):
        self.tubes = tubes
        self.hollow = hollow
        self.dropouts = dropouts or []

    def generate(self) -> str:
        parts = [self._header()]
        for tube in self.tubes:
            parts.append(self._make_tube(tube))
        for dropout in self.dropouts:
            parts.append(self._make_dropout(dropout))
        parts.append(self._footer())
        return "\n".join(parts)

    def _header(self) -> str:
        hollow_code = ""
        if self.hollow:
            hollow_code = """
    # Hollow tube: cut inner volume
    if wall > 0 and wall < min(r1, r2):
        ir1 = r1 - wall
        ir2 = r2 - wall
        if abs(ir1 - ir2) < 0.01:
            inner = Part.makeCylinder(ir1, length, s, direction)
        else:
            inner = Part.makeCone(ir1, ir2, length, s, direction)
        shape = outer.cut(inner)
"""
        return f'''\
"""FreeCAD macro generated by BCad2FreeCAD.

Open this file in FreeCAD and run it (Macro > Execute) to create
a 3D model of the bike frame.
"""

import FreeCAD
import Part

doc = FreeCAD.newDocument("BikeFrame")


def make_tube(name, start, end, r1, r2, wall=0, color=(0.6, 0.6, 0.65)):
    """Create a tube (cylinder or cone) from start to end."""
    s = FreeCAD.Vector(*start)
    e = FreeCAD.Vector(*end)
    direction = e - s
    length = direction.Length
    if length < 0.01:
        return None

    if abs(r1 - r2) < 0.01:
        outer = Part.makeCylinder(r1, length, s, direction)
    else:
        outer = Part.makeCone(r1, r2, length, s, direction)

    shape = outer
{hollow_code}
    obj = doc.addObject("Part::Feature", name)
    obj.Shape = shape
    obj.ViewObject.ShapeColor = color
    return obj


def make_dropout(name, center, width, height, thickness, slot_width,
                 slot_angle=180.0, slot_length=50.0, fillet=0.0, tabs=(),
                 color=(0.4, 0.4, 0.43)):
    """Create a parameterizedSocket dropout: slotted plate + stay-socket tabs.

    The plate lies in the X-Y plane and is `thickness` thick along Z. A U-slot
    of width `slot_width` and length `slot_length` (D, from the axle center to
    its rounded end) is cut opening in the direction `slot_angle` (degrees from
    +X, CCW: 0=forward, 90=up, 180/-180=rear, -90=down). Outer corners are
    rounded by `fillet`. Each entry in `tabs` is (start_xyz, dir_xyz, length,
    size): a socket stub from `start` along `dir`. Negative `size` means the
    stay tube inserts into the socket.
    """
    cx, cy, cz = center
    # Plate: box centered at (cx, cy) in X-Y, centered on cz in Z.
    plate = Part.makeBox(
        width, height, thickness,
        FreeCAD.Vector(cx - width / 2, cy - height / 2, cz - thickness / 2),
    )

    # Round the plate's vertical edges (those running along Z) before cutting
    # the slot, so only the outer corners get rounded. Guarded: a fillet
    # failure must not abort the whole macro.
    if fillet > 0:
        z_edges = [e for e in plate.Edges
                   if abs(e.Vertexes[0].Z - e.Vertexes[1].Z) > 1e-6]
        try:
            plate = plate.makeFillet(min(fillet, width / 2 - 0.1,
                                         height / 2 - 0.1), z_edges)
        except Exception:
            pass  # keep sharp corners if the fillet can't be applied

    # U-slot: a rectangle (slot_width x slot_length) with a rounded end — a box
    # fused with a cylinder cap at the far end (a "stadium"/capsule cross
    # section). Built along +X from the axle, then rotated by slot_angle. The
    # extra 1mm at the mouth keeps the cut clean where it opens.
    zt = thickness + 2.0
    z0 = cz - thickness / 2 - 1.0
    r = slot_width / 2
    slot = Part.makeBox(slot_length + 1.0, slot_width, zt,
                        FreeCAD.Vector(-1.0, -r, z0))
    cap = Part.makeCylinder(r, zt, FreeCAD.Vector(slot_length, 0, z0),
                            FreeCAD.Vector(0, 0, 1))
    slot = slot.fuse(cap)
    slot.rotate(FreeCAD.Vector(0, 0, cz), FreeCAD.Vector(0, 0, 1), slot_angle)
    slot.translate(FreeCAD.Vector(cx, cy, 0))
    shape = plate.cut(slot)

    # Stay-socket tabs: a cylinder from each socket point along its stay axis.
    for (sx, sy, sz), (dx, dy, dz), length, size in tabs:
        radius = max(abs(size), 0.5) / 2 + 2.0  # stub the tube fits over
        base = FreeCAD.Vector(sx, sy, sz)
        direction = FreeCAD.Vector(dx, dy, dz)
        if direction.Length < 1e-6:
            continue
        stub = Part.makeCylinder(radius, length, base, direction)
        shape = shape.fuse(stub)

    obj = doc.addObject("Part::Feature", name)
    obj.Shape = shape
    obj.ViewObject.ShapeColor = color
    return obj

'''

    def _make_tube(self, t: TubeSpec) -> str:
        s = t.start.tuple()
        e = t.end.tuple()
        wall = t.wall if self.hollow else 0
        return (
            f'make_tube("{t.name}",\n'
            f"    start=({s[0]:.2f}, {s[1]:.2f}, {s[2]:.2f}),\n"
            f"    end=({e[0]:.2f}, {e[1]:.2f}, {e[2]:.2f}),\n"
            f"    r1={t.radius1:.2f}, r2={t.radius2:.2f},\n"
            f"    wall={wall:.1f},\n"
            f"    color=({t.color[0]:.2f}, {t.color[1]:.2f}, {t.color[2]:.2f}))\n"
        )

    def _make_dropout(self, d: ParameterizedSocket) -> str:
        # Plate center = axle, shifted forward by Z (keeps axle fixed).
        cx = d.axle.x + d.Z
        cy = d.axle.y
        cz = d.axle.z
        # Footprint: axle hole plus A of material past the edge (A applied
        # once, not on both sides) → span = axle_dia + A.
        span = d.slotWidth + d.A

        tabs = []
        for sock in (d.chainstaySocket, d.seatstaySocket):
            if sock is None:
                continue
            start = (cx + sock.x, cy + sock.y, cz + sock.z)
            direction = (sock.axis.x, sock.axis.y, sock.axis.z)
            tabs.append((start, direction, d.tabLength, d.t))

        return (
            f'make_dropout("{d.name}",\n'
            f"    center=({cx:.2f}, {cy:.2f}, {cz:.2f}),\n"
            f"    width={span:.2f}, height={span:.2f}, thickness={d.T:.2f},\n"
            f"    slot_width={d.slotWidth:.2f}, slot_angle={d.slotAngle:.2f},\n"
            f"    slot_length={d.slotLength:.2f}, fillet={d.fillet:.2f}, "
            f"tabs={tabs!r},\n"
            f"    color=({d.color[0]:.2f}, {d.color[1]:.2f}, {d.color[2]:.2f}))\n"
        )

    def _footer(self) -> str:
        return """
doc.recompute()

# Fit the view if running in GUI mode
try:
    import FreeCADGui
    FreeCADGui.ActiveDocument.ActiveView.fitAll()
    FreeCADGui.SendMsgToActiveView("ViewFit")
except Exception:
    pass  # headless mode

print("BikeFrame created successfully with %d parts." % len(doc.Objects))
"""
